name: Deploy Frontend to Server

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

env:
  NODE_VERSION: '20'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT || 22 }}
        script: |
          # Create temporary deployment directory
          TEMP_DIR=$(mktemp -d)
          cd $TEMP_DIR

          # Clone repository
          git clone https://${{ secrets.TOKEN }}@github.com/${{ github.repository }}.git .

          # Install Node.js if not present
          if ! command -v node &> /dev/null; then
            curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
            sudo apt-get install -y nodejs
          fi

          # Install dependencies and generate
          npm ci
          NUXT_PUBLIC_API_BASE="${{ secrets.NUXT_PUBLIC_API_BASE }}" npm run generate

          # Clear existing files in /var/www/
          sudo rm -rf /var/www/*

          # Copy only generated files to /var/www/
          sudo cp -r .output/public/* /var/www/

          # Clean up temporary directory
          rm -rf $TEMP_DIR

          # Set correct permissions
          sudo chown -R www-data:www-data /var/www
          sudo chmod -R 755 /var/www